version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    expose:
      - "9000"
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - app-network

  db:
    image: mysql:${MYSQL_VERSION:-8.0}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app_db}
      MYSQL_USER: ${MYSQL_USER:-app_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-app_pass}
    ports:        
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:${PHPMYADMIN_VERSION:-5}
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"
    depends_on:
      - db

volumes:
  db_data:
  app_code:

networks:
  app-network:
    driver: bridge