version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile       # ของ PHP-FPM
    volumes:
      - ./src:/var/www/html
    expose:
      - "9000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

